[build]
  publish = "public"
  command = "npm run build"
  
[build.environment]
  NODE_VERSION = "14.15.0"
  
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"

[[plugins]]
  package = "@netlify/plugin-gatsby"

[[redirects]]
  from = "/*"
  to = "https://www.anbarasi.com"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}